apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  project: default
  source:
    chart: rook-ceph-cluster
    repoURL: https://charts.rook.io/release
    targetRevision: v1.17.0
    helm:
      valuesObject:
        operatorNamespace: rook-ceph
        cephClusterSpec:
          storage:
            useAllNodes: false
            useAllDevices: false
            deviceFilter: ""
            nodes:
              - name: tupu
                devices:
                  - name: /dev/disk/by-id/ata-APPLE_HDD_HTS541010A9E662_J5800013JD042A
              - name: lupu
                devices:
                  - name: /dev/disk/by-id/ata-APPLE_HDD_HTS541010A9E662_J890011VH53JT
          
        toolbox:
          enabled: true
        
        cephBlockPools:
          - name: ceph-blockpool
            # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md#spec for available configuration
            spec:
              failureDomain: host
              replicated:
                size: 1
                requireSafeReplicaSize: false
            storageClass:
              enabled: true
              name: ceph-block
              annotations: {}
              labels: {}
              isDefault: true
              reclaimPolicy: Delete
              allowVolumeExpansion: true
              volumeBindingMode: "Immediate"
              mountOptions: []
              # see https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
              allowedTopologies: []
              # see https://github.com/rook/rook/blob/master/Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md#provision-storage for available configuration
              parameters:
                imageFeatures: layering

                # These secrets contain Ceph admin credentials.
                csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: "{{ .Release.Namespace }}"
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
                csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
                # Specify the filesystem type of the volume. If not specified, csi-provisioner
                # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
                # in hyperconverged settings where the volume is mounted on the same node as the osds.
                csi.storage.k8s.io/fstype: ext4

  syncPolicy:
    automated:
      prune: true
