apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-library-pv
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.103
    path: /photos
  mountOptions:
    - nfsvers=4
  capacity:
    storage: 200Gi
