apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs-library-pvc
  namespace: immich
spec:
  storageClassName: ""
  volumeName: immich-nfs-library-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
