apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: node-feature-discovery
    server: https://kubernetes.default.svc
  project: default
  source:
    path: infrastructure/node-feature-discovery/resources
    repoURL: https://github.com/jonesus/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
