apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taulu
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  destination:
    namespace: taulu
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: apps/taulu/app
    repoURL: https://github.com/jonesus/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
