apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taulu-state-pvc
  namespace: taulu
spec:
  storageClassName: iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
