apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pilke-app-secrets
  namespace: pilke
spec:
  encryptedData:
    SECRET_KEY: AgBUPwnqEP0rs2jDFT7DwpvLE04pqcSFXvJClXOcYAqYtbvyMCu7eDTPgsr3NChZ/6v7Zu+VV5Ut8G/QVX9IO7hJzVaTeaVyNZV8omyXoEbkrBOnM7nrtf9PjIRdDiRJRqb8vwgfigiLcnUlY5XkilLBWyUjwlkkF8JildP5R1ungSIZvpbB2xKRkzTsfjoBsLl5wMYDYS3eDciW+YdwLfEUYpGzLWZGeVXGiJwj1V0yVXX4r/DOPLAlP5ut1Tun9vJctYSzWkyZUmQnURxHK1LtehASp9P4sLp8A/NFb8TF4bhCxs60TzjRFq2phWr79KbB+cUxcmO6sFWtaLeHMaZdgbygtnJi8hafeptHELXRXybAdxAOzjGylint+9fNudWxWfbYRWAAREo/lvE8KfPA/t4R83mhHg/J/mhULIP1xutX2pCk/m8P48s49XlK1RxtFApSwU8pCHS+ilIrun6Vlmabs9vSLBFaj1yV8Js73ZL+yblZ88R0t98bcez+QTrczZTaIZKAwSG7IJzkJ28aHcBvvtp74xS8xUwmzpxD/S8zT4Do8YQFLm08PMP0EOor3pR4RAcX2qZrTHR5+ByYl64beHsXodRqFuSqdv7nsFbdKAK6dB4Z3imZKzvkxB1uLjdPnzWD40gigV3vrBcuW/jKfmd+3MIr1kt7fcN16L0ZRYLBoqMhXDDxRsiT48ku2S1YjBKzeefDea+iBMKxjsdZSGAsSjzUf9YWbGVYaLyUDfPt3kJZhNnfa59swgCSmIJBEedmY9vGLTjb11y9SCq/aUdOwu4BInI51fRapJZNHmNzng==
  template:
    metadata:
      creationTimestamp: null
      name: pilke-app-secrets
      namespace: pilke
    type: Opaque

