apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pilke-postgres-user
  namespace: pilke
spec:
  encryptedData:
    password: AgAAX4MjAGUdnfB/PM3G8uYlxFlvciAp8bq1GOu8L3/hsnmOXWY9ADclBZ9U8dZh/VKLLV3BfCZSq93t20nASuRO6n3WqoAtaHmFLLzk8DVKW9PruJgukgjucMtDbZ2HPnl4GkxbBbfA89gh2AnfjD9gCxZT/RHgmdsjZxGZBepNdbABIMJwhlxHQ7DzY9Q/BdnyE3U7ALr7yt0jbp1bc5J+ynQYQaEAdkS7IEyHbewybY8D0l+N10+N7rebzxcUl76bCJJb2AMfkfC0q3jXdd7UFPeLZkdDzAbfF9QboLIbbyBiP3uQKAFB6H/Dpvid5/7EcwB0HvHbpHmMLr0uUEhjbu9ujrOjk/TgLZ1BUkBs/irJgPdtgouhXx+9RntHREYmTG+YLJXGmOPRbyenzfdn3TT2+gs2C2ahdBTUEAm8m7zURfXMtyZ1bzwDFG4Srv2We2tMyJHRN3BONXUt+s9hkLh+xAy2Z4ZtUAYFiD3PVxQvC29WROsTsRtlhS5GhIChYUVPLU1yQvPKSediARL4pLGmX+TbKspkfwnRU5cRXnXkW07hUyEffFMOezV4RXt4GTdCYsam/zbiKgN7gFD0vyVdz5C0Oewk4gmojZQGMCxb5hoXMvFvAZj7iuJRQEwFHguDqk8Q1n7wSfD6ix3vkzUNHVMon9Ows4qZ/uH+4JZgxToe8/zRvjl1bIWqr4Kv0v3QPba+xnub2/Cgg7tVCKKIpRRvEAYWPcWUM4zv61Cm6eNy1rkK/iWU5tYQIgFGvaEl0j4p3yifryl6Kpav
    username: AgCPn5ljPzpHLLzNHK3CCVae/cfSHEXOaliKCEkeD6IOZsBBWmeDmkqdH/31vW/RlnlvZHY1l2gn1M+kTbp2K9fxyHMUmWh/1VCyiomXzunk1xQlr+wn66bgmYUPJnvXVwdWv6SGZIiFAJZMHh8IdxCukM01oF/np7cM3rgIQ+yPZEYgpj73Lear1CVKzQdVsLhFLtxPm6zkT49YCixyGX5JRE/DgclLehcdgLmjyF7VQEaxwpMFKeJCdhCRB99/3nBFb+fLFym3+pt2YvRl+DzK+JGIaj9v39kL/vSIw99a68N49lRUxOz7KJYHPucpoJTMjfOe9nmwL0XDIGP0sTZDNk7vd1Z2B8PesXJcFidZUcXc4EQq2fng6oxWgbExJ+f5dn6Mr5GmpH71LKp3LIVkXD89Tk7Tt8GHhZ3IaJM0QPtymBzS78J+oNv6BATeRpMaajoOVOB80n52/VRfFg1eeGsuhi0F0UMhyg9cTWMBcI8epWjiP1VFcXsU7ed84/4wQQvRCzeo/C7z/Q+Swj+JLeuW8SX7Xyn9Lsa0ZXcXmKCzvbg9SA+1zKByWS+TaYyOdx1BJa0dvA/vhA0ta/Ag8u+2ArKMlpb7Gfg/Ctb8jMGjmclyNijsM4daz6ulg/Ul0sSRqKMhjPg/maz8YMqmBn832KnogJca5ivwlIjxjyokjPmjWZZNan+TNXuat2ZN2IwQ7Oww
  template:
    metadata:
      creationTimestamp: null
      name: pilke-postgres-user
      namespace: pilke
    type: kubernetes.io/basic-auth

