apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - database.yaml
  - database-user.sealed.yaml
  - app-secrets.sealed.yaml
  - ghcr-pull.sealed.yaml

namespace: pilke
