apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-secrets
  namespace: garage
spec:
  encryptedData:
    admin-token: AgAA6aLNb7srTBgI5yRAM+9+ORPhvgIn/5Rif6ws5Uqi96/PHoD0mNU8NmNyAIAuZQjZFMMW0cxUFUpLLWrkdwV+Y8D1WHftRQfGMQghBTkLlm1e0SdPn/OOp6oZjgeAsgoyOBVostWQM9Z80ov8s9YSAujpgLPtO2Br9gah7jAisdbiAW9p26AVzGTvbEuD6pFjY20566agIrrDCmMVKp39rxF3N+mYCwATWR+S7Ybar+hcK+orT96euW4n1eZe1ZAzwdnpYQHrLO4socUlfOqFWjROtxtD2qyzS/lx6gcF2iXIEYPYBIycIiIXuvSvHyNwr9yh1b+cJc28J9zi80RVdTRT3MVRKmSLfI122U1/3LBmE16Z2p/0wcAgjatWxFuWafMfWPAmcQJ0/BUz/UPPkPbhRZabMFk0r0Io6e4NUTF+ih2mcatYccRBdFBEz4195hbtMgK6si0W4VRktgePE3yi9glkIkgH43iKddVMzpeJHlOcYgAf8pNjroBNoaP7LU3nPmHFDcmDuJKW7GzoME3D4DEJkQGPvLZGj8YBfBO2XoQS22ufsb3+rsU1MJUDi5a7ozx+b93CLLBoYyNxDxwS3hojTED0vAYXsPrJqqidx/grFUkI/5bgcVs7e2gCFPfSPI2mOWfHtNl5W6igwXWC2uPNbN3yEsYslomqqyM+z1IsuVAzoAUq790IQN77eqjKylt/sp39xoXRE2ejrDv1kt6ZpF3Vcg13ZsD2o+ps5xIFMpPi0mWPdA==
    rpc-secret: AgAxhRtqPHpPiqBxeXdLAyX7EhvN2sGCTC4qfGrZ5hDv53szEHI4G59b0DYz0M+uzT1Dpp19QJbZq8tqcLtVNiCfSpei2NBozwfmKhGTfEXx/um4A8HABQW8KIsLfnm5uaBeq0kris2bapGYPtkxKE+ssYS2YkbggtkixMvKbkyyfBfZemIc775XwYaBZP0H2iREq/FKBoQji6jbTh1GL5T73XAVYrr2+95GE7fozbHuNvC8YpnR1Hg0A8BMdQ3rymsp82WMxYqa1lirh2wOkVPgl6MSfuMt++58VsvG5Ia35G7o9dHF4X6+7w3LmWM3naQOX3gy7nhg/Mcu35++CGzKXPDNe3pcpAksA57rVwGP/CfwModciKHjVj0yt6YDO3w1Dyl5EMOe8yslLL8ZbTYfM9tmKdcySb6WYCNNXG7DTDAexy+BJym1dT5TzCkWtWjBdKvl60eS0NQ9MKQNBvquGfqypU1H2qt+5P5yBbDdWJZoUiIU0NnpKjeOL1WJc10tSp2i6JawGBw/4NBlg5V4OOrkBh8R16uycXSyt5r+kQKzRNjfbYrf01Fyn0wwqad4yood1IUSHWAF7ivXt8xOanPvZPVLsriLOOPRZWl9zMVlScf5TWyo12WRwXGwQ/ka7YAXoimGbLz/LZEK2ycGlZBfFUeUr9vpGGEaAXsRtU3PDyA0U1fuDDPv1FshGc+NxLPopSreGahUFg8T/d4IA42rdvV7rBik2FAssEcLVCNixr1J+3XPNdl7SSIvGH0R7Zk7fgnp2o3tKNHjiVuK
  template:
    metadata:
      creationTimestamp: null
      name: garage-secrets
      namespace: garage
    type: Opaque

