apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-device-plugin
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: intel-device-plugin
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: intel-device-plugins-operator
    repoURL: https://intel.github.io/helm-charts
    targetRevision: 0.32.0
    helm:
      releaseName: intel-device-plugins-operator
      valuesObject:
        manager:
          devices:
            gpu: true
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
