apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-photos-dest-pvc
  namespace: immich
spec:
  storageClassName: ""
  volumeName: backup-photos-dest-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
