apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-photos-source-pvc
  namespace: immich
spec:
  storageClassName: ""
  volumeName: backup-photos-source-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 200Gi
