apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backup-source-pv.yaml
  - backup-source-pvc.yaml
  - backup-dest-pv.yaml
  - backup-dest-pvc.yaml
  - cronjob.yaml

namespace: immich
