apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt-prerequisites
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: apps/zigbee2mqtt/prerequisites
    repoURL: https://github.com/jonesus/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
