apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mosquitto
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homeassistant
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: apps/mosquitto
    repoURL: https://github.com/jonesus/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
