apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: homeassistant
data:
  mosquitto.conf: |
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    
    # MQTTS listener
    listener 8883
    protocol mqtt

    # WS Listener
    listener 9001
    protocol websockets