apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-mosquitto-pvc
  namespace: homeassistant
spec:
  storageClassName: ""
  volumeName: nas-mosquitto-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
