---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gandi-pat
  namespace: external-dns
spec:
  encryptedData:
    GANDI_PAT: AgBlWvqmH0mHtVV1nalfJ8ReDKcytPqmHxsUvyes52Oy/H2ixZVVhJ94uxai7mCQI7GTv+/RNMkabA8xDBXnWjwGFxFB88IWIa7QquOkucB4FMBY9fwQT09yGZ1UmPV8BDp4DttgbqJsuKkS0/IL2ZWy+llJXnuzwN2eapsvxrtWzNF8kxDs08ChD2UKqB2pqLhkkvXyLdsWJm7DbUJBhBU4vIPtbKHWGtp8rHV8qSUcEUtRro+oK77ilUy5lPZb08N2bOtMellea0vleQBbXrjEOsuS4WUPyqtsMKmpXKDYn2j3nlCbyRuU+ZBuWcPgxzdUMFUtXgJht8girziWh2f/eHLXhEx3CrJl7uFyQKpbN2r1hpXFyq65naV2enmOLmNbwXpwusYXUmwjBhgau5DyAjDJZqBSUwL4scyexTUcs97rq/npTWqJpG4zvFEgvpeA4UG774CB93zDdz6CyaTIjZi3OM3zj1zZ1OyjbnoCimkPKZftqgaoG9vLd0ceCLED4G0rvWHKUX6tmdDlwzzJ4kaQ2r+3EUPpPlmaUXfNISAQ2r+FTL5mKle0uXC5Xis3JpvKbUwnMtmcF2yZSWCWLeeEptyX84Jr+kLUN5zorWO5WsThw2iDYnrMGeSD73y1BrPrExVxOKe+FUudt8q+g43BAYx2KNsNd4gktGCcOgFEK81Hcqjo92srIX+WoB1oaHRM57jPk0hDQGwESDpkOJe8lPFaaxjpEDKvlyJKW5RmdAHgIAmq
  template:
    metadata:
      creationTimestamp: null
      name: gandi-pat
      namespace: external-dns
