---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gandi-pat
  namespace: external-dns
spec:
  encryptedData:
    GANDI_PAT: AgBjQv0vCrZRJt9Q9+MjDU6IkMaVXadhGZ9qj0daR07KKT+Nbso90umOeUdblXi9NKCAztAk3OnzQSMg/AWBEU8Gi26vG1D6mYsPKb1SfM166aS1Qm2mExGz7RO9JkkRe6UTb0Hqhj9i/Kv65uvCoVXaQiEJGJzZxY5FUa/BRkqV9gsqZWThLN/OU6Kx/6GxUsY33MK53h+xgSPcAnPmdf+k/c34ADaxgnPU247AL5S2hcn+2hGU+J/V/NpIxRomCKw5bGl8ZjGGUUGHY9Wb7yQg537Uf9bFKKJ9sXKM8qsM/N7UmaS3xbBMGLvWJB1/haHwurAycqL51kZkrRwduPRCmMjWF1hzjgr0KrwI5YjTFyRdLCyhU8zsX2YRKHdOyfJ0KRPUQM6TvRigE7KwY1o7jO/lkBFBEKe5HISWQMxYzKiltzg08AE/VioxSvaJ5U68xdrijFIhztbcWF1MCTfakshLNXd6Q1uyg9j/Q/E1iKiLqOtroevT5JzLb70iYwq+XKaHWDrCKQRwfhb3vmP6cKASv/vDRMwS85fpyTKHq5v8uPQZFRaOsQ1fHeAsA05K0653uIhduY9fC7Tv4eLLEZ7JEcZHSdCyBZKem5tFMCc1xtxDkajyoIOyfQE6cttJ4qqXz+t85RtoLZXj9oHwzoFU8s3hK0/q9VdRPXjImNqVJHu1/YGGWFlv2SmRQpteqE4ggn8QRGARj/gRnq/WoIJVlQYlf2+HGtWr+WSXhIjularTDQbW
  template:
    metadata:
      name: gandi-pat
      namespace: external-dns
