apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux-prerequisites
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  destination:
    namespace: miniflux
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: apps/miniflux/prerequisites
    repoURL: https://github.com/jonesus/homelab
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
