apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd/app.yaml
  - metallb/app.yaml
  - metallb/resources.yaml
  - ingress-nginx/app.yaml
  - sealed-secrets/app.yaml
  - external-dns/app.yaml
  - cert-manager/app.yaml
  - cert-manager/resources.yaml
