apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zone-configurator-config
  namespace: homeassistant
spec:
  storageClassName: iscsi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
