apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - holvi-proxy/app.yaml
  - calibre/app.yaml
  - redis/app.yaml
  - immich/app.yaml
  - immich/prerequisites.yaml
  - vaultwarden/app.yaml
  - zigbee2mqtt/app.yaml
  - mosquitto/app.yaml
  - rethink/app.yaml
  - matter-server/app.yaml
  - homeassistant/app.yaml
  - ha-mcp/app.yaml
  - miniflux/app.yaml
  - miniflux/prerequisites.yaml
  - paperless/app.yaml
  - paperless/prerequisites.yaml
  - taulu/app.yaml
  - taulu/prerequisites.yaml
  - backup-photos/app.yaml
  - internal-ingresses/app.yaml
