---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: esphome-secrets
  namespace: homeassistant
spec:
  encryptedData:
    secrets.yaml: AgC2/MlkZ/kHt7J5SxWQF9g65/1ZKv9Xd3Jbi/ZLrSL24cyEUIudINW8KsR296z8VoHESn3tBIEKm0UCmoswG8bePP3geA4cWEJ8VLcbBpfvwihhCp/XB8L4GZ4U3QXpXC7P/z7A1BnySNTj8IosEfIogXSJ0t/kAg9+EMnacJqsNuiDG8F+Gg84oPFf1XqXXznK1R6grhhDvPWUqgQX0u/pLKN/6jebEfZISnoMeFIRN+Ukez3RSxpsLWO8AJ+lWmZWZ7bz6TsbeEtXL2fcuuxUeTqZYIC85COxuTGZnr1S+6oDq2SzoLsowPEzzTCx76RBo2Ief0EdY1WJir1zweBrY/jtRDI1YR3tBmYopWJH48lk36K+V6UrISNijN8UwpnOpBYFef+XHMs7z4clrwsU1t2IzZRgjvF5P6bRVdMNVJw7dDgTcXqPAEEg1JIgN9r3vGu7K4PM12yCbNLO4TwnoYoPpwu8PK1aU6zavR5w/F5wCOJfWgp3zpwhptE33vEvhfi/YXHBUltWS7xtU5KRo4Z0g1ner+f+JmY2juPQVabnzlSKG7/q2xEuBSBl1av2uWyK84bGP4BHx18N38DGsY60fZbPQGlRVEFZu9ZrLjAduI3wXtbeD0ofmPh6CyUOCmCLS/1pdZz7eO82O6vxPZ3jPhpYYC6iP2j7e0QhuklOz6CnjXYUhF8p6BgsOWPSeVLCv7U6vbN+v3EPkPobo4TKSn5qGiNMVupw0TMlSB4ATyUkB8aJBR+UWJODsa/V3VKeYrq/VDTgVkr0ql2p1ki+qD+sN8Jafk0+ieXASZMByCgDBckXf2mLwE/6bOtpHxhM5twaWbJyoG1DCtqAlFcB1SfWFwoZojgpKwOonMoNF0/MSOQuoM7V4bp8hJe9vyAkIoGM3tttDKu84bhGCT4NpWUz9aJCOQrkCwxRlr/N9tkx4+kzbaUIagpZ1ul1mMNNssjqqQd9djORzuXEDNxR5/LV8rY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: esphome-secrets
      namespace: homeassistant

