apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-redis-pvc
  namespace: redis
spec:
  storageClassName: ""
  volumeName: nas-redis-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
