apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-calibre-pvc
  namespace: calibre
spec:
  storageClassName: ""
  volumeName: nfs-calibre-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
