apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-nas-config-pv
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 192.168.1.103:3260
    iqn: iqn.2004-04.com.qnap:ts-469pro:iscsi.adguard.d3a579
    lun: 0
    fsType: ext4
    readOnly: false
  capacity:
    storage: 1Gi
