apiVersion: v1
kind: ConfigMap
metadata:
  name: rethink-config
  namespace: homeassistant
data:
  config.json: |
    {
      "hostname": "rethink-cloud.internal",
      "state": "/state",
      "ca_key": "/state/ca.key",
      "ca_cert": "/state/ca.cert",
      "https_port": 4433,
      "thinq1_https_port": 46030,
      "thinq1_port": 47878,
      "mqtt_port": 1884,
      "mqtts_port": 8884,
      "management_port": 44401,
      "mqtt": {
        "url": "mqtt://mosquitto.homeassistant:8883",
        "discovery_prefix": "homeassistant"
      },
      "bridge": {
        "enabled": true
      }
    }
