apiVersion: v1
kind: ConfigMap
metadata:
  name: rethink-config
  namespace: homeassistant
data:
  config.json: |
    {
      "hostname": "rethink-cloud.internal",
      "homeassistant": {
        "mqtt_url": "mqtt://mosquitto.homeassistant.svc.cluster.local:8883",
        "discovery_prefix": "homeassistant",
        "rethink_prefix": "rethink",
        "mqtt_user": "",
        "mqtt_pass": ""
      },
      "ca_key_file": "/state/ca.key",
      "ca_cert_file": "/state/ca.cert",
      "https_port": 4433,
      "mqtts_port": 8884,
      "mqtt_port": 1884,
      "thinq1_https_port": 46030,
      "thinq1_port": 47878,
      "management_port": 44401,
      "bridge": {
        "storage_path": "/state"
      },
      "log": ["status", "incoming", "HTTPS", "publish", "MGMT"]
    }
